#!/usr/bin/env python3
"""
Security Now! NomadNet Page

Displays daily security news digest in Steve Gibson's style.
Connects to security_host.py backend on localhost:6001.
"""
import os
from multiprocessing.connection import Client

# Get parameters from NomadNet
view = os.environ.get("var_view", "latest")  # latest, archive, list
date = os.environ.get("var_date", None)

# Auth key - set via environment
authkey = os.environ.get("SN_AUTHKEY", "insecure").encode()

# Cache for 1 hour (content changes daily)
print("#!c=3600")


def send_cmd(conn, command, **kwargs):
    """Send command to backend and get response."""
    kwargs["command"] = command
    conn.send(kwargs)
    resp = conn.recv()
    return resp


def format_micron(content: str) -> str:
    """
    Convert markdown-ish digest content to Micron markup.

    Handles:
    - ## Headers -> >>Header
    - **bold** -> `!bold`!
    - *italic* -> `*italic`*
    - --- -> -
    - URLs -> clickable links
    """
    lines = []

    for line in content.split('\n'):
        # Headers
        if line.startswith('## '):
            lines.append(f"\n>>{line[3:]}")
        elif line.startswith('### '):
            lines.append(f"\n>>>{line[4:]}")
        elif line.startswith('# '):
            lines.append(f"\n>{line[2:]}")

        # Horizontal rules
        elif line.strip() == '---':
            lines.append('-')

        # Bold and italic (simple replacement)
        else:
            # Bold: **text** -> `!text`!
            import re
            line = re.sub(r'\*\*([^*]+)\*\*', r'`!\1`!', line)
            # Italic: *text* -> `*text`*
            line = re.sub(r'\*([^*]+)\*', r'`*\1`*', line)

            # URLs - make them visible but not clickable (NomadNet limitation)
            # Keep them as-is for now, they'll display as text

            lines.append(line)

    return '\n'.join(lines)


def show_latest(conn):
    """Display the latest digest."""
    resp = send_cmd(conn, "get_latest")

    if resp.get("status") != "ok":
        print(">Security Now! - Error")
        print("")
        print(resp.get("message", "Unknown error"))
        print("")
        print("The digest service may not be running or no digests have been generated yet.")
        return

    print(">Security Now! Daily Digest")
    print(f"`*{resp['date']}  |  Model: {resp.get('model_version', 'unknown')}`*")
    print("")
    print("`F0af`[View Archives`:/page/sn.mu`view=list]`f")
    print("-")
    print("")

    # Format and display content
    content = format_micron(resp['content'])
    print(content)

    print("")
    print("-")
    print("`F888`*Generated by fine-tuned Mistral 7B in Steve Gibson's style`*`f")


def show_archive(conn, date_str: str):
    """Display a specific archived digest."""
    resp = send_cmd(conn, "get_archive", date=date_str)

    if resp.get("status") != "ok":
        print(">Security Now! - Archive Not Found")
        print("")
        print(resp.get("message", f"No digest for {date_str}"))
        print("")
        print("`F0af`[Back to Archives`:/page/sn.mu`view=list]`f")
        return

    print(f">Security Now! - {resp['date']}")
    print("")
    print("`F0af`[Latest Digest`:/page/sn.mu`view=latest]`f   `F0af`[All Archives`:/page/sn.mu`view=list]`f")
    print("-")
    print("")

    content = format_micron(resp['content'])
    print(content)

    print("")
    print("-")
    print(f"`F888`*Generated: {resp.get('generated_at', 'unknown')}`*`f")


def show_archive_list(conn):
    """Display list of available digests."""
    resp = send_cmd(conn, "list_archives", limit=30)

    if resp.get("status") != "ok":
        print(">Security Now! - Error")
        print(resp.get("message", "Unknown error"))
        return

    dates = resp.get("dates", [])

    print(">Security Now! Archives")
    print("")
    print("`F0af`[Latest Digest`:/page/sn.mu`view=latest]`f")
    print("-")
    print("")

    if not dates:
        print("No archived digests yet.")
        print("")
        print("Digests are generated daily. Check back soon!")
        return

    print(f"Available digests ({len(dates)} total):")
    print("")

    for d in dates:
        print(f"  `F55a`[{d}`:/page/sn.mu`view=archive|date={d}]`f")

    print("")
    print("-")
    print("`[Home`:/page/index.mu]")


def show_error(message: str):
    """Display error page."""
    print(">Security Now! - Connection Error")
    print("")
    print(f"`F66d{message}`f")
    print("")
    print("The Security Now! backend service may not be running.")
    print("")
    print("To start it:")
    print("`=python projects/security_now/security_host.py`=")
    print("")
    print("`[Home`:/page/index.mu]")


# Main logic
try:
    conn = Client(('localhost', 6001), authkey=authkey)

    if view == "list":
        show_archive_list(conn)
    elif view == "archive" and date:
        show_archive(conn, date)
    else:
        show_latest(conn)

    conn.close()

except ConnectionRefusedError:
    show_error("Could not connect to backend service (connection refused)")
except Exception as e:
    show_error(f"Error: {e}")
